name: Deploy site to S3 + CloudFront
on:
  push:
    branches: [ main ]

env:
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DIST_ID: ${{ vars.CF_DIST_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload index (no-cache)
        run: |
          aws s3 cp build/index.html s3://$S3_BUCKET/index.html \
            --content-type "text/html" \
            --cache-control "no-cache, no-store, must-revalidate"

      - name: Sync remaining files (long cache)
        run: |
          aws s3 sync build s3://$S3_BUCKET --exclude "index.html" \
            --cache-control "public, max-age=2592000, immutable"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/index.html"
